version: "3.8"

services:
  blogsphere.api.gateway:
    image: ${DOCKER_REGISTRY-}blogsphereapigateway
    build:
      context: .
      dockerfile: Blogsphere.Api.Gateway/Dockerfile
  gatewaydb:
    image: postgres

  gatewaydbviewer:
    image: dpage/pgadmin4:9.5

volumes:
  gatewaydbdata:
  gatewaydbviewerdata:

networks:
  blogsphere_dev_net:
    external: true
