version: "3.8"

services:
  blogsphere.api.gateway:
    container_name: Blogsphere.Api.Gateway
    depends_on:
      - gatewaydb
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - Logging__IncludeScopes=false
      - "Logging__LogOutputTemplate=[{Timestamp:dd-MM-yyyy HH:mm:ss, fff}] {Level} {Properties} [CorrelationId:{CorrelationId}] [Machine: {MachineName}] {CallerType}:{MemberName} {Message}{NewLine}{Exception}{NewLine}"
      - Logging__Console__Enabled=true
      - Logging__Console__LogLevel=Debug
      - Logging__Elastic__Enabled=true
      - Logging__Elastic__LogLevel=Debug
      - AppConfigurations__ApplicationIdentifier=Blogsphere.Api.Gateway
      - AppConfigurations__ApplicationEnvironment=docker
      - ElasticSearch__Uri=http://elasticsearch:9200
      - "ConnectionStrings__DefaultConnection=Server=gatewaydb;Database=BlogsphereProxy;Username=admin;Password=admin"
      - "Zipkin__Url=http://zipkin:9411/api/v2/spans"
      - "ApiDescription=Proxy API Gateway"
      - "ApiOriginHost=localhost:8000"
      - "IdentityGroupAccess__Authority=http://host.docker.internal:5000"
      - "IdentityGroupAccess__Audience=blogsphere.api.gateway"
      - "AllowedHosts=*"
      - "EventBus__Host=rabbitmq"
      - "EventBus__Username=guest"
      - "EventBus__Password=guest"
      - "EventBus__VirtualHost=/"
      - "EventBus__Port=5672"
    networks:
      - blogsphere_dev_net

  gatewaydb:
    container_name: gatewaydb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=BlogsphereProxy
    ports:
      - "5432:5432"
    volumes:
      - gatewaydbdata:/var/lib/postgresql/data
    networks:
      - blogsphere_dev_net

  gatewaydbviewer:
    container_name: gatewaydbviewer
    depends_on:
      - gatewaydb
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@blogsphere.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - gatewaydbviewerdata:/root/.pgadmin
    networks:
      - blogsphere_dev_net
