version: "3.8"

services:
  gatewaydb:
    image: postgres

  gatewaydbviewer:
    image: dpage/pgadmin4:9.5

volumes:
  gatewaydbdata:
  gatewaydbviewerdata:

networks:
  blogsphere_dev_net:
    external: true
